spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIA_URL}
    username: ${MARIA_USER}
    password: ${MARIA_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
jwt:
  secret-key: ${SECRET_KEY}
  expiration: 7200
  refresh-token:
    expiration: 604800