spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  security:
    oauth2:
      client:
        provider:
          kakao:
            user-info-uri: https://kapi.kakao.com/v2/user/me
          naver:
            user-info-uri: https://openapi.naver.com/v1/nid/me
  h2:
    console:
      enabled: true
  elasticsearch:
    host: ${ELASTIC_HOST}
    port: ${ELASTIC_PORT}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}

management:
  health:
    elasticsearch:
      enabled: false

jwt:
  secret-key: ${SECRET_KEY}
  expiration: 7200
  refresh-token:
    expiration: 604800

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  version: 'v1'
  swagger-ui:
    operationsSorter: method
    disable-swagger-default-url: true
    path: /api/v1/docs/swagger
  paths-to-match:
    - /**
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    stack:
      auto: false
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    cloudfront:
      domain: ${AWS_CLOUDFRONT_DOMAIN}