spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secret-key: ${SECRET_KEY}
  expiration: 7200
  refresh-token:
    expiration: 604800