spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  security:
    oauth2:
      client:
        provider:
          kakao:
            user-info-uri: https://kapi.kakao.com/v2/user/me
          naver:
            user-info-uri: https://openapi.naver.com/v1/nid/me
  h2:
    console:
      enabled: true
jwt:
  secret-key: ${SECRET_KEY}
  expiration: 7200
  refresh-token:
    expiration: 604800